ACTIVE_SCHOOL_NAMES = [
    "UC Davis School of Medicine",
    "University of California San Diego School of Medicine",
    "Kaiser Permanente Bernard J. Tyson School of Medicine",
    "Keck School of Medicine of USC",
    "University of Rochester School of Medicine and Dentistry",
    "University of Colorado School of Medicine",
    "Lewis Katz School of Medicine at Temple University",
    "Emory University School of Medicine",
    "University of Cincinnati College of Medicine",
    "Geisel School of Medicine at Dartmouth",
    "Tufts University School of Medicine",
    "The Ohio State University College of Medicine",
    "Boston University Chobanian & Avedisian School of Medicine",
    "Virginia Tech Carilion School of Medicine",
    "University of Virginia School of Medicine",
    "Vermont Larner College of Medicine",
    "University of Wisconsin School of Medicine and Public Health",
    "Medical College of Wisconsin",
    "Sidney Kimmel Medical College at Thomas Jefferson University",
    "University of Iowa Roy J. and Lucille A. Carver College of Medicine",
    "Western Michigan University Homer Stryker M.D. School of Medicine",
    "University of Miami Leonard M. Miller School of Medicine",
    "Wake Forest University School of Medicine",
    "Albany Medical College",
    "Drexel University College of Medicine",
    "Wayne State University School of Medicine",
    "Loyola University Chicago Stritch School of Medicine",
    "Frank H. Netter M.D. School of Medicine at Quinnipiac University",
    "Tulane University School of Medicine",
    "Eastern Virginia Medical School",
    "Rush Medical College at Rush University",
    "Chicago Medical School at Rosalind Franklin University of Medicine and Science",
    "New York Medical College",
    "University of California, Riverside School of Medicine",
    "California University of Science and Medicine",
]


NEW_SCHOOLS = [
    {
        "name": "Albany Medical College",
        "slug": "albany",
        "secondary_cycle": "2025-2026 from Admit.org / Med School Insiders",
        "secondary_deadline": "December 1, 2025",
        "official_url": "https://www.amc.edu/academic/undergraduate-medical-education/admissions/",
        "prompt_source": "https://med.admit.org/secondary-essays/albany-medical-college",
        "notes": "Large prompt set with strong overlap in challenge, community, and social-determinants essays.",
        "prompts": [
            {
                "title": "Describe Yourself",
                "limit": "1000 characters",
                "themes": ["community", "values"],
                "text": "Describe yourself.",
            },
            {
                "title": "Academic Inconsistencies",
                "limit": "1000 characters",
                "themes": ["academic-context"],
                "text": "Please explain any inconsistencies in your university, graduate, or professional school academic performance and/or MCAT scores. If the question does not apply to you, please put N/A in the box provided.",
            },
            {
                "title": "Interrupted Attendance or Gaps",
                "limit": "1000 characters",
                "themes": ["gap-year", "academic-context"],
                "text": "Has your college or university, graduate or professional school attendance been interrupted for any reason? If yes, please explain. Also, please explain any extended gaps in activity/employment in your post-graduate history. If the question does not apply to you, please put N/A in the box provided.",
            },
            {
                "title": "Significant Challenge",
                "limit": "1000 characters",
                "themes": ["challenge"],
                "text": "Describe a significant challenge that has prepared you for the MD career path.",
            },
            {
                "title": "Structural and Social Determinants of Health",
                "limit": "1000 characters",
                "themes": ["service", "diversity-equity"],
                "text": "Please describe your personal experiences with the structural and social determinants of health in your life and community, how they shaped your engagement with medicine and your future ideas for doctoring.",
            },
            {
                "title": "Community Identity",
                "limit": "1000 characters",
                "themes": ["community"],
                "text": "Tell us about a community with which you identify and how you are involved with it.",
            },
            {
                "title": "Anything Else",
                "limit": "1000 characters",
                "themes": ["additional-info"],
                "text": "Is there anything else you would like the admissions committee to know when reviewing your application? If so, please use the space provided.",
            },
            {
                "title": "Most Meaningful Activity Impact",
                "limit": "1000 characters",
                "themes": ["clinical", "service"],
                "text": "In the Work and Activities section on your AMCAS application, select the experience that has been the most meaningful in influencing your desire to pursue a career in medicine, explain why, and describe what aspect of that experience best equips you to make an impact in the medical profession.",
            },
        ],
    },
    {
        "name": "Drexel University College of Medicine",
        "slug": "drexel",
        "secondary_cycle": "2025-2026 from Admit.org / Med School Insiders",
        "secondary_deadline": "January 1, 2026",
        "official_url": "https://drexel.edu/medicine/admissions/apply/",
        "prompt_source": "https://med.admit.org/secondary-essays/drexel-university-college-of-medicine",
        "notes": "Compact prompt set with direct overlap across why-school, current-year, and context essays.",
        "prompts": [
            {
                "title": "Current and Recent Activities",
                "limit": "2000 characters",
                "themes": ["gap-year", "clinical", "service"],
                "text": "Please discuss all of your current and recent activities and engagements that have prepared you for medical school. Please be sure to include any traditional and/or non-traditional clinical exposures and volunteering experiences that you have done that are not already included in your application.",
            },
            {
                "title": "Why Drexel and Mission Fit",
                "limit": "1500 characters",
                "themes": ["why-school", "mission-fit"],
                "text": "Why are you interested in Drexel? Please also explain how you meet various elements of our mission - compassionate care, diversity, spirited inquiry, collaboration, and opportunity.",
            },
            {
                "title": "Extenuating Circumstances",
                "limit": "1500 characters",
                "themes": ["additional-info", "academic-context"],
                "text": "Please describe any extenuating circumstances that may have affected your medical or non-medical service experiences, including any circumstances that impacted your engagement in activities, academics, and MCAT that would have helped to prepare you for medical school.",
            },
        ],
    },
    {
        "name": "Wayne State University School of Medicine",
        "slug": "wayne-state",
        "secondary_cycle": "2025-2026 from Med School Insiders",
        "secondary_deadline": "Advised within 2 weeks of request; final deadline February 8, 2026",
        "official_url": "https://www.med.wayne.edu/admissions",
        "prompt_source": "https://medschoolinsiders.com/medical-school-secondary-prompts-database/wayne-state-university-school-of-medicine-secondary-essay-prompts/",
        "notes": "Urban mission and belonging prompts line up especially well with service, justice, and community work.",
        "prompts": [
            {
                "title": "Motivation and Challenges of Medicine",
                "limit": "1250 characters",
                "themes": ["future-goals", "challenge"],
                "text": "When reflecting on the roles and responsibilities of a physician, please discuss what motivated your interest. What are potential challenges to pursuing a career in medicine?",
            },
            {
                "title": "Healthcare Challenges in Under-Resourced Communities",
                "limit": "1250 characters",
                "themes": ["service", "diversity-equity"],
                "text": "What are the healthcare challenges faced by under-resourced communities in the U.S.? Why do these healthcare challenges exist? How would you address them?",
            },
            {
                "title": "Mission Alignment",
                "limit": "1250 characters",
                "themes": ["mission-fit"],
                "text": "Which of your experiences and activities align with WSU SOM's mission? Please discuss how they align.",
            },
            {
                "title": "Belonging and Class Contribution",
                "limit": "1250 characters",
                "themes": ["diversity-equity", "community"],
                "text": "The Wayne State University School of Medicine aims to provide a rich, varied, and inclusive educational experience for all members of the class. How would you advance belonging and contribute to the educational experience of fellow medical students?",
            },
            {
                "title": "Growth Year",
                "limit": "No word count specified",
                "themes": ["gap-year"],
                "text": "Please answer if you have had a gap or growth year (career change, re-applicant, additional education, etc.). A growth year is defined as a period of time between the end of your undergraduate education and a year or more prior to the start of medical school. What activities have you participated in or plan to participate in during this period? How does this relate to your future career in medicine?",
            },
        ],
    },
    {
        "name": "Loyola University Chicago Stritch School of Medicine",
        "slug": "loyola-stritch",
        "secondary_cycle": "2025-2026 from Med School Insiders",
        "secondary_deadline": "December 12, 2025",
        "official_url": "https://www.luc.edu/stritch/admissions/",
        "prompt_source": "https://medschoolinsiders.com/medical-school-secondary-prompts-database/loyola-university-secondary-essay-prompts/",
        "notes": "Prompt set centers on Jesuit mission, social justice, service, disagreement, and professional challenge.",
        "prompts": [
            {
                "title": "Jesuit Mission Resonance",
                "limit": "500 words",
                "themes": ["why-school", "mission-fit"],
                "text": "As you consider Loyola University Chicago Stritch School of Medicine, please tell us what resonates with you regarding our mission as a Jesuit, Catholic medical school? Consider also what you may be curious about regarding our institutional mission and identity.",
            },
            {
                "title": "Why Medicine",
                "limit": "500 words",
                "themes": ["future-goals", "clinical"],
                "text": "Considering all that you could do with your life, how have you discerned your decision to become a physician? What is particular to the practice of medicine and the vocation of a physician that draws you to apply to medical school versus another helping/caring profession? What experiences, conversations, and encounters have informed your decision to apply?",
            },
            {
                "title": "Social Justice and Under-Resourced Communities",
                "limit": "500 words",
                "themes": ["service", "diversity-equity"],
                "text": "Social justice, in the Jesuit tradition, justice due to each person's inherent human dignity, is an essential dimension of education at SSOM. Describe an impactful experience working with and for under-resourced communities. Explain what you have learned about yourself through this service and/or what has hindered your efforts to serve others in these environments.",
            },
            {
                "title": "Disagreeing with Feedback",
                "limit": "500 words",
                "themes": ["challenge", "values"],
                "text": "Describe a time you received feedback about your performance and disagreed with the feedback. What did you disagree with? How did you handle it?",
            },
            {
                "title": "Non-Academic Challenge or Conflict",
                "limit": "500 words",
                "themes": ["challenge"],
                "text": "Describe a non-academic personal/professional challenge or conflict that you have experienced. Explain what skills, resources and/or strategies you employed to resolve the problem.",
            },
            {
                "title": "Updates and Context",
                "limit": "Open update field",
                "themes": ["additional-info"],
                "text": "Please indicate additional grades earned, amendments to your proposed coursework or graduation date, address changes, additions to your list of experiences, and anything else you feel we should know.",
            },
            {
                "title": "Gaps, Delays, or Academic Missteps",
                "limit": "1500 characters",
                "themes": ["academic-context", "additional-info"],
                "text": "Please explain in more detail anything that would help us understand any gaps or delays in your education, academic missteps, or personal challenges not listed elsewhere.",
            },
            {
                "title": "If Out of Coursework for Two Years",
                "limit": "Open field if applicable",
                "themes": ["gap-year"],
                "text": "If you have not been enrolled in coursework for over two years, please let us know what you have been doing since your coursework ended.",
            },
            {
                "title": "Reapplicant Improvement",
                "limit": "Open field if applicable",
                "themes": ["additional-info", "gap-year"],
                "text": "Have you applied to SSOM prior to this application? If so, please list the years of your previous application submissions to SSOM and tell us how your application has improved since your previous submission.",
            },
        ],
    },
    {
        "name": "Frank H. Netter M.D. School of Medicine at Quinnipiac University",
        "slug": "quinnipiac-netter",
        "secondary_cycle": "2025-2026 from Med School Insiders",
        "secondary_deadline": "December 1, 2025",
        "official_url": "https://medicine.qu.edu/admissions/",
        "prompt_source": "https://medschoolinsiders.com/medical-school-secondary-prompts-database/quinnipiac-frank-netter-secondary-essay-prompts/",
        "notes": "Strong overlap across gap-year, lived-experience, uncertainty, service, and academic context prompts.",
        "prompts": [
            {
                "title": "Application Year Plan",
                "limit": "200 words",
                "themes": ["gap-year"],
                "text": "If you will not be enrolled as a full-time student, how will you be spending or intend to spend your time during your application year? If you are a re-applicant, please address steps taken to improve your application for medical school.",
            },
            {
                "title": "Specialty Interests and Future Career",
                "limit": "200 words",
                "themes": ["future-goals"],
                "text": "Although your interests may change, how do you currently envision your specialty interests and future career in medicine and why?",
            },
            {
                "title": "Lived Experiences and Patient Care",
                "limit": "200 words",
                "themes": ["diversity-equity"],
                "text": "Tell us about your lived experiences that will enable you to provide quality care to all patients.",
            },
            {
                "title": "Beyond Your Capabilities",
                "limit": "400 words",
                "themes": ["challenge"],
                "text": "As a medical student and future physician, you will be faced with many uncertain situations. Please describe a situation when you were asked to do something that was beyond your capabilities. How did you handle the situation? Please provide a specific example.",
            },
            {
                "title": "Service with People from Different Backgrounds",
                "limit": "400 words",
                "themes": ["service", "diversity-equity"],
                "text": "At Netter SOM, we value service to each other and others in the community. Please share how you have made efforts to work with people from a different background than you. What did you learn from these efforts?",
            },
            {
                "title": "Withdrawals or Breaks",
                "limit": "250 words",
                "themes": ["academic-context"],
                "text": "If applicable, please address any withdrawals, repeated courses, leaves of absence or breaks in your undergraduate education that are not explained in your application.",
            },
        ],
    },
    {
        "name": "Tulane University School of Medicine",
        "slug": "tulane",
        "secondary_cycle": "2024 archive on Admit.org",
        "secondary_deadline": "November 1, 2025",
        "official_url": "https://medicine.tulane.edu/admissions",
        "prompt_source": "https://med.admit.org/secondary-essays/tulane-university",
        "notes": "Short prompts; useful to keep concise reusable blocks for why-school, New Orleans fit, leadership, and hobbies.",
        "prompts": [
            {
                "title": "Why Tulane",
                "limit": "150 words",
                "themes": ["why-school", "mission-fit"],
                "text": "Tulane University School of Medicine's mission statement states: We improve human health and foster healthy communities through discovery and translation of the best science into clinical practice and education; to deliver the highest quality patient care and prepare the next generation of distinguished clinical and scientific leaders. Briefly describe the reasons for your interest in Tulane University School of Medicine.",
            },
            {
                "title": "New Orleans Health Disparities",
                "limit": "150 words",
                "themes": ["service", "diversity-equity"],
                "text": "What disparities in health do you believe are pertinent to the New Orleans patient population? How would you attempt to address them as a medical student at Tulane? You may support your answer by using past involvement working in a similar patient population to compare and/or describe your interest in any student activities offered at Tulane or in New Orleans.",
            },
            {
                "title": "How Others Describe You",
                "limit": "150 words",
                "themes": ["values"],
                "text": "Who knows you best and how would they describe you?",
            },
            {
                "title": "Leadership Positions",
                "limit": "100 words",
                "themes": ["teamwork", "values"],
                "text": "Please list any leadership positions (clubs, organizations, paid work) you may have held.",
            },
            {
                "title": "Hobbies and Interests",
                "limit": "150 words",
                "themes": ["community"],
                "text": "Please list your hobbies and major non-academic interests.",
            },
            {
                "title": "Underrepresented Group",
                "limit": "60 words",
                "themes": ["diversity-equity"],
                "text": "Tulane University School of Medicine values the diversity of its patients, faculty, staff, and students. Do you identify with a particular group that you believe is underrepresented among medical professionals?",
            },
            {
                "title": "COVID Impact",
                "limit": "150 words",
                "themes": ["additional-info"],
                "text": "In what ways did the COVID-19 pandemic alter or interrupt your medical school application?",
            },
        ],
    },
    {
        "name": "Eastern Virginia Medical School",
        "slug": "eastern-virginia",
        "secondary_cycle": "2025-2026 from Med School Insiders",
        "secondary_deadline": "December 31, 2025",
        "official_url": "https://www.evms.edu/education/medical_programs/doctor_of_medicine/admissions/",
        "prompt_source": "https://medschoolinsiders.com/medical-school-secondary-prompts-database/eastern-virginia-med-school-secondary-essay-prompts/",
        "notes": "Directly aligned to exposure to medicine, future self, and school-specific rationale.",
        "prompts": [
            {
                "title": "Exposure to Medicine",
                "limit": "2000 characters",
                "themes": ["clinical"],
                "text": "Briefly describe your exposure to medicine.",
            },
            {
                "title": "What You Will Like Best About Being a Physician",
                "limit": "2000 characters",
                "themes": ["future-goals"],
                "text": "What do you think you will like best about being a physician?",
            },
            {
                "title": "What You Will Like Least About Being a Physician",
                "limit": "2000 characters",
                "themes": ["challenge", "future-goals"],
                "text": "What do you think you will like least about being a physician?",
            },
            {
                "title": "Ten Years from Now",
                "limit": "2000 characters",
                "themes": ["future-goals"],
                "text": "Describe yourself and your medical career as you see it ten years from now.",
            },
            {
                "title": "Why EVMS",
                "limit": "2000 characters",
                "themes": ["why-school"],
                "text": "Please indicate your reasons for applying to VHS-EVMS at ODU.",
            },
        ],
    },
    {
        "name": "Rush Medical College at Rush University",
        "slug": "rush",
        "secondary_cycle": "2025-2026 from Med School Insiders",
        "secondary_deadline": "November 15, 2025",
        "official_url": "https://www.rushu.rush.edu/rush-medical-college/admissions",
        "prompt_source": "https://medschoolinsiders.com/medical-school-secondary-prompts-database/rush-medical-college-secondary-essay-prompts/",
        "notes": "Current prompt set emphasizes worldview, distance traveled, challenge, and health equity.",
        "prompts": [
            {
                "title": "Worldview and Understanding Difference",
                "limit": "1000 characters",
                "themes": ["diversity-equity"],
                "text": "Rush Medical College is located on Chicago's Near West Side and serves a diverse patient population. We seek to train physicians who can connect with diverse patient populations with whom they may not share a similar background. Tell us about a life experience that has broadened your own world view or enhanced your ability to understand those unlike yourself and what you learned from this experience.",
            },
            {
                "title": "Distance Traveled - Adversities",
                "limit": "1000 characters",
                "themes": ["challenge", "diversity-equity"],
                "text": "Distance traveled is the metaphorical distance that represents the journey an applicant undertakes throughout their life, encompassing achievements, personal identity, and the competencies developed along the way. Based on your experiences and your distance traveled, please describe any adversities, challenges, and/or marginalized experiences that you have encountered. Optional.",
            },
            {
                "title": "Distance Traveled - Effect and Growth",
                "limit": "1000 characters",
                "themes": ["challenge"],
                "text": "Please describe the effect of these adversities, challenges, and/or marginalized experiences on you as an individual. Explain how you overcame them, what skills you built, what lessons you learned, and how these experiences motivated you to be a doctor. Optional.",
            },
            {
                "title": "Privilege and Health Equity",
                "limit": "1000 characters",
                "themes": ["service", "diversity-equity"],
                "text": "Can you describe a time when you recognized your privilege and used it to promote health equity? Please share specific initiatives, projects, or actions in which you were involved in and the impact they had. Optional.",
            },
        ],
    },
    {
        "name": "Chicago Medical School at Rosalind Franklin University of Medicine and Science",
        "slug": "rosalind-franklin",
        "secondary_cycle": "2025-2026 from Med School Insiders",
        "secondary_deadline": "December 1, 2025",
        "official_url": "https://www.rosalindfranklin.edu/admission-aid/",
        "prompt_source": "https://medschoolinsiders.com/medical-school-secondary-prompts-database/chicago-med-school-rosalind-franklin-secondary-essay-prompts/",
        "notes": "Very concise 150-word essays; useful to draft as tight vignettes instead of traditional long-form secondaries.",
        "prompts": [
            {
                "title": "Why Medicine",
                "limit": "150 words",
                "themes": ["future-goals", "clinical"],
                "text": "What inspired you to pursue a career in medicine, and how have your personal experiences or background shaped your desire to become a physician?",
            },
            {
                "title": "Challenge or Setback",
                "limit": "150 words",
                "themes": ["challenge"],
                "text": "Tell us about a time when you faced a significant challenge or setback. How did you navigate it, and what did you learn from the experience that will help you succeed in medical school?",
            },
            {
                "title": "Empathy in Difficult Times",
                "limit": "150 words",
                "themes": ["service", "values"],
                "text": "Describe an experience where you helped someone who was going through a difficult time. How did you approach the situation, and what did you learn about the importance of empathy in providing care?",
            },
            {
                "title": "Self-Consciousness and Growth",
                "limit": "150 words",
                "themes": ["challenge", "values"],
                "text": "Is there anything about yourself that you feel self-conscious about? How have you addressed it, and what have you learned about yourself through this process?",
            },
            {
                "title": "Two Passions",
                "limit": "150 words",
                "themes": ["future-goals", "values"],
                "text": "What are two causes or activities you are most passionate about? How do these passions reflect your values and goals as a future physician?",
            },
            {
                "title": "Optional DEI Statement",
                "limit": "150 words",
                "themes": ["diversity-equity"],
                "text": "Rosalind Franklin University of Medicine and Science continuously strives to advance diversity, equity, and inclusion (DEI). Each applicant's lived experience provides an opportunity to contribute to our mission. Please share the ways in which your personal experiences, values, qualities and perspectives will enrich RFU and our community. Optional.",
            },
        ],
    },
    {
        "name": "New York Medical College",
        "slug": "new-york-medical-college",
        "secondary_cycle": "2024 archive on Admit.org",
        "secondary_deadline": "December 15, 2025",
        "official_url": "https://www.nymc.edu/school-of-medicine-som/admissions/",
        "prompt_source": "https://med.admit.org/secondary-essays/new-york-medical-college",
        "notes": "Secondary is mostly attestation and context oriented rather than classic narrative essays.",
        "prompts": [
            {
                "title": "Family Connection",
                "limit": "No word limit",
                "themes": ["additional-info"],
                "text": "If you have family members with a connection to NYMC as alumni, faculty, or employees of the School of Medicine, indicate the relationship and applicable connection details.",
            },
            {
                "title": "Social Media Policy Explanation",
                "limit": "No word limit",
                "themes": ["additional-info"],
                "text": "Please review the NYMC Social Media Policy. If you select YES, we ask that you briefly explain what has been posted.",
            },
            {
                "title": "COVID Disruptions",
                "limit": "No word limit",
                "themes": ["additional-info"],
                "text": "Please share any disruptions in your academic, volunteer, work, and/or personal life related to COVID-19 that you would like the Admissions Committee to consider.",
            },
            {
                "title": "Technical Standards Attestation",
                "limit": "No word limit",
                "themes": ["additional-info"],
                "text": "Please review the NYMC Technical Standards on the admissions website and attest to your understanding of them.",
            },
        ],
    },
    {
        "name": "University of California, Riverside School of Medicine",
        "slug": "uc-riverside",
        "secondary_cycle": "2024 archive on Admit.org",
        "secondary_deadline": "October 15, 2025",
        "official_url": "https://medschool.ucr.edu/admissions",
        "prompt_source": "https://med.admit.org/secondary-essays/university-of-california-riverside-school-of-medicine",
        "notes": "Mission-forward and strongly regional; these drafts should explicitly mention underserved Inland Southern California where appropriate.",
        "prompts": [
            {
                "title": "Mission Fit and Class Contribution",
                "limit": "250 words",
                "themes": ["mission-fit", "service"],
                "text": "The mission of the UCR School of Medicine is to improve the health of the people of California and, especially, to serve Inland Southern California by training a diverse workforce of physicians and by developing innovative research and health care delivery programs that will improve the health of the medically underserved in the region and become models to be emulated throughout the state and nation. What experiences, skills, and abilities will you bring to the class to fulfill this mission?",
            },
            {
                "title": "School Value in Practice",
                "limit": "250 words",
                "themes": ["values"],
                "text": "The values of the UCR SOM are integrity, innovation, inclusion, excellence, accountability and respect. Please choose one of the values and tell us how you have personally experienced it or have seen it emulated in a clinical setting.",
            },
            {
                "title": "Future Healthcare Setting",
                "limit": "250 words",
                "themes": ["future-goals"],
                "text": "In what type of healthcare setting do you see yourself practicing medicine?",
            },
            {
                "title": "Personal Challenge, Resilience, and Grit",
                "limit": "250 words",
                "themes": ["challenge"],
                "text": "Tell us about a personal challenge you have faced in your life thus far and how you demonstrated resilience and grit to overcome it. Please do not write about studying for or taking the MCAT.",
            },
            {
                "title": "Anything Else",
                "limit": "250 words",
                "themes": ["additional-info"],
                "text": "If there is anything you would like the committee to consider about your candidacy that is not explained elsewhere in your application, please use this space to tell us.",
            },
        ],
    },
    {
        "name": "California University of Science and Medicine",
        "slug": "cusm",
        "secondary_cycle": "2025-2026 from Admit.org / Med School Insiders",
        "secondary_deadline": "December 30, 2025",
        "official_url": "https://cusm.edu/admissions/",
        "prompt_source": "https://med.admit.org/secondary-essays/california-university-of-science-and-medicine",
        "notes": "Very short prompts; best handled as polished mini-essays with clean thematic separation.",
        "prompts": [
            {
                "title": "Diversity Contribution",
                "limit": "150 words",
                "themes": ["diversity-equity"],
                "text": "Diversity comes in many forms. How do you think you might contribute to the diversity of the class?",
            },
            {
                "title": "Criticism",
                "limit": "150 words",
                "themes": ["challenge", "values"],
                "text": "Describe the last time you were criticized by a peer or supervisor. How did you handle it?",
            },
            {
                "title": "Working with a Difficult Person",
                "limit": "150 words",
                "themes": ["teamwork", "challenge"],
                "text": "Give an example of when you had to work with someone who was difficult to get along with. Why was this person difficult? How did you handle that person?",
            },
            {
                "title": "Integrity",
                "limit": "150 words",
                "themes": ["values"],
                "text": "What would be the best example that shows you are a person of integrity?",
            },
            {
                "title": "Ten Years from Now",
                "limit": "150 words",
                "themes": ["future-goals"],
                "text": "If given the opportunity to attend medical school, where would you see yourself in ten years?",
            },
            {
                "title": "Underloaded Terms Explanation",
                "limit": "150 words",
                "themes": ["academic-context"],
                "text": "If you were enrolled in fewer than 12 units or credits for more than 1 semester or 2 quarters during your undergraduate education, please provide a brief explanation. If not applicable, enter N/A.",
            },
        ],
    },
]
