ACTIVE_SCHOOL_NAMES = [
    "UC Davis School of Medicine",
    "University of California San Diego School of Medicine",
    "Kaiser Permanente Bernard J. Tyson School of Medicine",
    "Lewis Katz School of Medicine at Temple University",
    "Emory University School of Medicine",
    "Virginia Tech Carilion School of Medicine",
    "Vermont Larner College of Medicine",
    "University of Wisconsin School of Medicine and Public Health",
    "Medical College of Wisconsin",
    "Sidney Kimmel Medical College at Thomas Jefferson University",
    "University of Miami Leonard M. Miller School of Medicine",
    "Wake Forest University School of Medicine",
    "Albany Medical College",
    "Drexel University College of Medicine",
    "Wayne State University School of Medicine",
    "Loyola University Chicago Stritch School of Medicine",
    "Frank H. Netter M.D. School of Medicine at Quinnipiac University",
    "Tulane University School of Medicine",
    "Eastern Virginia Medical School",
    "Rush Medical College at Rush University",
    "Chicago Medical School at Rosalind Franklin University of Medicine and Science",
    "New York Medical College",
    "University of California, Riverside School of Medicine",
    "California University of Science and Medicine",
    "University of Massachusetts Chan Medical School",
    "Nova Southeastern University Dr. Kiran C. Patel College of Allopathic Medicine",
    "Roseman University College of Medicine",
    "Hackensack Meridian School of Medicine",
    "Thomas F. Frist, Jr. College of Medicine at Belmont University",
    "University of Illinois College of Medicine",
    "George Washington University School of Medicine & Health Sciences",
    "California Northstate University College of Medicine",
]


NEW_SCHOOLS = [
    {
        "name": "Albany Medical College",
        "slug": "albany",
        "secondary_cycle": "2025-2026 from Admit.org / Med School Insiders",
        "secondary_deadline": "December 1, 2025",
        "official_url": "https://www.amc.edu/academic/undergraduate-medical-education/admissions/",
        "prompt_source": "https://med.admit.org/secondary-essays/albany-medical-college",
        "notes": "Large prompt set with strong overlap in challenge, community, and social-determinants essays.",
        "prompts": [
            {
                "title": "Describe Yourself",
                "limit": "1000 characters",
                "themes": ["community", "values"],
                "text": "Describe yourself.",
            },
            {
                "title": "Academic Inconsistencies",
                "limit": "1000 characters",
                "themes": ["academic-context"],
                "text": "Please explain any inconsistencies in your university, graduate, or professional school academic performance and/or MCAT scores. If the question does not apply to you, please put N/A in the box provided.",
            },
            {
                "title": "Interrupted Attendance or Gaps",
                "limit": "1000 characters",
                "themes": ["gap-year", "academic-context"],
                "text": "Has your college or university, graduate or professional school attendance been interrupted for any reason? If yes, please explain. Also, please explain any extended gaps in activity/employment in your post-graduate history. If the question does not apply to you, please put N/A in the box provided.",
            },
            {
                "title": "Significant Challenge",
                "limit": "1000 characters",
                "themes": ["challenge"],
                "text": "Describe a significant challenge that has prepared you for the MD career path.",
            },
            {
                "title": "Structural and Social Determinants of Health",
                "limit": "1000 characters",
                "themes": ["service", "diversity-equity"],
                "text": "Please describe your personal experiences with the structural and social determinants of health in your life and community, how they shaped your engagement with medicine and your future ideas for doctoring.",
            },
            {
                "title": "Community Identity",
                "limit": "1000 characters",
                "themes": ["community"],
                "text": "Tell us about a community with which you identify and how you are involved with it.",
            },
            {
                "title": "Anything Else",
                "limit": "1000 characters",
                "themes": ["additional-info"],
                "text": "Is there anything else you would like the admissions committee to know when reviewing your application? If so, please use the space provided.",
            },
            {
                "title": "Most Meaningful Activity Impact",
                "limit": "1000 characters",
                "themes": ["clinical", "service"],
                "text": "In the Work and Activities section on your AMCAS application, select the experience that has been the most meaningful in influencing your desire to pursue a career in medicine, explain why, and describe what aspect of that experience best equips you to make an impact in the medical profession.",
            },
        ],
    },
    {
        "name": "Drexel University College of Medicine",
        "slug": "drexel",
        "secondary_cycle": "2025-2026 from Admit.org / Med School Insiders",
        "secondary_deadline": "January 1, 2026",
        "official_url": "https://drexel.edu/medicine/admissions/apply/",
        "prompt_source": "https://med.admit.org/secondary-essays/drexel-university-college-of-medicine",
        "notes": "Compact prompt set with direct overlap across why-school, current-year, and context essays.",
        "prompts": [
            {
                "title": "Current and Recent Activities",
                "limit": "2000 characters",
                "themes": ["gap-year", "clinical", "service"],
                "text": "Please discuss all of your current and recent activities and engagements that have prepared you for medical school. Please be sure to include any traditional and/or non-traditional clinical exposures and volunteering experiences that you have done that are not already included in your application.",
            },
            {
                "title": "Why Drexel and Mission Fit",
                "limit": "1500 characters",
                "themes": ["why-school", "mission-fit"],
                "text": "Why are you interested in Drexel? Please also explain how you meet various elements of our mission - compassionate care, diversity, spirited inquiry, collaboration, and opportunity.",
            },
            {
                "title": "Extenuating Circumstances",
                "limit": "1500 characters",
                "themes": ["additional-info", "academic-context"],
                "text": "Please describe any extenuating circumstances that may have affected your medical or non-medical service experiences, including any circumstances that impacted your engagement in activities, academics, and MCAT that would have helped to prepare you for medical school.",
            },
        ],
    },
    {
        "name": "Wayne State University School of Medicine",
        "slug": "wayne-state",
        "secondary_cycle": "2025-2026 from Med School Insiders",
        "secondary_deadline": "Advised within 2 weeks of request; final deadline February 8, 2026",
        "official_url": "https://www.med.wayne.edu/admissions",
        "prompt_source": "https://medschoolinsiders.com/medical-school-secondary-prompts-database/wayne-state-university-school-of-medicine-secondary-essay-prompts/",
        "notes": "Urban mission and belonging prompts line up especially well with service, justice, and community work.",
        "prompts": [
            {
                "title": "Motivation and Challenges of Medicine",
                "limit": "1250 characters",
                "themes": ["future-goals", "challenge"],
                "text": "When reflecting on the roles and responsibilities of a physician, please discuss what motivated your interest. What are potential challenges to pursuing a career in medicine?",
            },
            {
                "title": "Healthcare Challenges in Under-Resourced Communities",
                "limit": "1250 characters",
                "themes": ["service", "diversity-equity"],
                "text": "What are the healthcare challenges faced by under-resourced communities in the U.S.? Why do these healthcare challenges exist? How would you address them?",
            },
            {
                "title": "Mission Alignment",
                "limit": "1250 characters",
                "themes": ["mission-fit"],
                "text": "Which of your experiences and activities align with WSU SOM's mission? Please discuss how they align.",
            },
            {
                "title": "Belonging and Class Contribution",
                "limit": "1250 characters",
                "themes": ["diversity-equity", "community"],
                "text": "The Wayne State University School of Medicine aims to provide a rich, varied, and inclusive educational experience for all members of the class. How would you advance belonging and contribute to the educational experience of fellow medical students?",
            },
            {
                "title": "Growth Year",
                "limit": "No word count specified",
                "themes": ["gap-year"],
                "text": "Please answer if you have had a gap or growth year (career change, re-applicant, additional education, etc.). A growth year is defined as a period of time between the end of your undergraduate education and a year or more prior to the start of medical school. What activities have you participated in or plan to participate in during this period? How does this relate to your future career in medicine?",
            },
        ],
    },
    {
        "name": "Loyola University Chicago Stritch School of Medicine",
        "slug": "loyola-stritch",
        "secondary_cycle": "2025-2026 from Med School Insiders",
        "secondary_deadline": "December 12, 2025",
        "official_url": "https://www.luc.edu/stritch/admissions/",
        "prompt_source": "https://medschoolinsiders.com/medical-school-secondary-prompts-database/loyola-university-secondary-essay-prompts/",
        "notes": "Prompt set centers on Jesuit mission, social justice, service, disagreement, and professional challenge.",
        "prompts": [
            {
                "title": "Jesuit Mission Resonance",
                "limit": "500 words",
                "themes": ["why-school", "mission-fit"],
                "text": "As you consider Loyola University Chicago Stritch School of Medicine, please tell us what resonates with you regarding our mission as a Jesuit, Catholic medical school? Consider also what you may be curious about regarding our institutional mission and identity.",
            },
            {
                "title": "Why Medicine",
                "limit": "500 words",
                "themes": ["future-goals", "clinical"],
                "text": "Considering all that you could do with your life, how have you discerned your decision to become a physician? What is particular to the practice of medicine and the vocation of a physician that draws you to apply to medical school versus another helping/caring profession? What experiences, conversations, and encounters have informed your decision to apply?",
            },
            {
                "title": "Social Justice and Under-Resourced Communities",
                "limit": "500 words",
                "themes": ["service", "diversity-equity"],
                "text": "Social justice, in the Jesuit tradition, justice due to each person's inherent human dignity, is an essential dimension of education at SSOM. Describe an impactful experience working with and for under-resourced communities. Explain what you have learned about yourself through this service and/or what has hindered your efforts to serve others in these environments.",
            },
            {
                "title": "Disagreeing with Feedback",
                "limit": "500 words",
                "themes": ["challenge", "values"],
                "text": "Describe a time you received feedback about your performance and disagreed with the feedback. What did you disagree with? How did you handle it?",
            },
            {
                "title": "Non-Academic Challenge or Conflict",
                "limit": "500 words",
                "themes": ["challenge"],
                "text": "Describe a non-academic personal/professional challenge or conflict that you have experienced. Explain what skills, resources and/or strategies you employed to resolve the problem.",
            },
            {
                "title": "Updates and Context",
                "limit": "Open update field",
                "themes": ["additional-info"],
                "text": "Please indicate additional grades earned, amendments to your proposed coursework or graduation date, address changes, additions to your list of experiences, and anything else you feel we should know.",
            },
            {
                "title": "Gaps, Delays, or Academic Missteps",
                "limit": "1500 characters",
                "themes": ["academic-context", "additional-info"],
                "text": "Please explain in more detail anything that would help us understand any gaps or delays in your education, academic missteps, or personal challenges not listed elsewhere.",
            },
            {
                "title": "If Out of Coursework for Two Years",
                "limit": "Open field if applicable",
                "themes": ["gap-year"],
                "text": "If you have not been enrolled in coursework for over two years, please let us know what you have been doing since your coursework ended.",
            },
            {
                "title": "Reapplicant Improvement",
                "limit": "Open field if applicable",
                "themes": ["additional-info", "gap-year"],
                "text": "Have you applied to SSOM prior to this application? If so, please list the years of your previous application submissions to SSOM and tell us how your application has improved since your previous submission.",
            },
        ],
    },
    {
        "name": "Frank H. Netter M.D. School of Medicine at Quinnipiac University",
        "slug": "quinnipiac-netter",
        "secondary_cycle": "2026-2027 live secondary portal prompts provided by applicant on 2026-07-08",
        "secondary_deadline": "December 1, 2025",
        "official_url": "https://medicine.qu.edu/admissions/",
        "prompt_source": "https://medschoolinsiders.com/medical-school-secondary-prompts-database/quinnipiac-frank-netter-secondary-essay-prompts/",
        "notes": "Strong overlap across gap-year, lived-experience, uncertainty, service, and academic context prompts.",
        "prompts": [
            {
                "title": "Application Year Plan",
                "limit": "200 words",
                "themes": ["gap-year"],
                "text": "If you will not be enrolled as a full-time student, how will you be spending or intend to spend your time during your application year? If you are a re-applicant, please address steps taken to improve your application for medical school.",
            },
            {
                "title": "Specialty Interests and Future Career",
                "limit": "200 words",
                "themes": ["future-goals"],
                "text": "Although your interests may change, how do you currently envision your specialty interests and future career in medicine and why?",
            },
            {
                "title": "Lived Experiences and Patient Care",
                "limit": "200 words",
                "themes": ["diversity-equity"],
                "text": "Tell us about your lived experiences that will enable you to provide quality care to all patients.",
            },
            {
                "title": "Beyond Your Capabilities",
                "limit": "400 words",
                "themes": ["challenge"],
                "text": "As a medical student and future physician, you will be faced with many uncertain situations. Please describe a situation when you were asked to do something that was beyond your capabilities. How did you handle the situation? Please provide a specific example.",
            },
            {
                "title": "Service with People from Different Backgrounds",
                "limit": "400 words",
                "themes": ["service", "diversity-equity"],
                "text": "At Netter SOM, we value service to each other and others in the community. Please share how you have made efforts to work with people from a different background than you. What did you learn from these efforts?",
            },
            {
                "title": "Withdrawals or Breaks",
                "limit": "250 words",
                "themes": ["academic-context"],
                "text": "If applicable, please address any withdrawals, repeated courses, leaves of absence or breaks in your undergraduate education that are not explained in your application.",
            },
        ],
    },
    {
        "name": "Tulane University School of Medicine",
        "slug": "tulane",
        "secondary_cycle": "2026-2027 live secondary portal prompts provided by applicant on 2026-07-09",
        "secondary_deadline": "November 1, 2025",
        "official_url": "https://medicine.tulane.edu/admissions",
        "prompt_source": "https://medapp.tulane.edu/Security/Login.aspx",
        "notes": "Updated from the applicant's Tulane secondary portal. Live pasted set contains three 150-word prompts.",
        "prompts": [
            {
                "title": "Why Tulane",
                "limit": "150 words",
                "themes": ["why-school", "mission-fit"],
                "text": "Tulane University School of Medicine’s mission statement states: We improve human health and foster healthy communities through discovery and translation of the best science into clinical practice and education; to deliver the highest quality patient care and prepare the next generation of distinguished clinical and scientific leaders. Briefly describe how this statement resonates with your desire to attend Tulane University School of Medicine.",
            },
            {
                "title": "New Orleans Health Disparities",
                "limit": "150 words",
                "themes": ["service", "diversity-equity"],
                "text": "What disparities in health do you believe are pertinent to the New Orleans community or similar patient populations? How would you attempt to address them as a medical student at Tulane? You may support your answer by using demonstrated past involvement working with similar patient populations to compare and/or describe your interest in any student experience offered at TUSOM or in New Orleans.",
            },
            {
                "title": "How Others Describe You",
                "limit": "150 words",
                "themes": ["values"],
                "text": "Who knows you best and how would they describe you?",
            },
        ],
    },
    {
        "name": "Eastern Virginia Medical School",
        "slug": "eastern-virginia",
        "secondary_cycle": "2025-2026 from Med School Insiders",
        "secondary_deadline": "December 31, 2025",
        "official_url": "https://www.evms.edu/education/medical_programs/doctor_of_medicine/admissions/",
        "prompt_source": "https://medschoolinsiders.com/medical-school-secondary-prompts-database/eastern-virginia-med-school-secondary-essay-prompts/",
        "notes": "Directly aligned to exposure to medicine, future self, and school-specific rationale.",
        "prompts": [
            {
                "title": "Exposure to Medicine",
                "limit": "2000 characters",
                "themes": ["clinical"],
                "text": "Briefly describe your exposure to medicine.",
            },
            {
                "title": "What You Will Like Best About Being a Physician",
                "limit": "2000 characters",
                "themes": ["future-goals"],
                "text": "What do you think you will like best about being a physician?",
            },
            {
                "title": "What You Will Like Least About Being a Physician",
                "limit": "2000 characters",
                "themes": ["challenge", "future-goals"],
                "text": "What do you think you will like least about being a physician?",
            },
            {
                "title": "Ten Years from Now",
                "limit": "2000 characters",
                "themes": ["future-goals"],
                "text": "Describe yourself and your medical career as you see it ten years from now.",
            },
            {
                "title": "Why EVMS",
                "limit": "2000 characters",
                "themes": ["why-school"],
                "text": "Please indicate your reasons for applying to VHS-EVMS at ODU.",
            },
        ],
    },
    {
        "name": "Rush Medical College at Rush University",
        "slug": "rush",
        "secondary_cycle": "2025-2026 from Med School Insiders",
        "secondary_deadline": "November 15, 2025",
        "official_url": "https://www.rushu.rush.edu/rush-medical-college/admissions",
        "prompt_source": "https://medschoolinsiders.com/medical-school-secondary-prompts-database/rush-medical-college-secondary-essay-prompts/",
        "notes": "Current prompt set emphasizes worldview, distance traveled, challenge, and health equity.",
        "prompts": [
            {
                "title": "Worldview and Understanding Difference",
                "limit": "1000 characters",
                "themes": ["diversity-equity"],
                "text": "Rush Medical College is located on Chicago's Near West Side and serves a diverse patient population. We seek to train physicians who can connect with diverse patient populations with whom they may not share a similar background. Tell us about a life experience that has broadened your own world view or enhanced your ability to understand those unlike yourself and what you learned from this experience.",
            },
            {
                "title": "Distance Traveled - Adversities",
                "limit": "1000 characters",
                "themes": ["challenge", "diversity-equity"],
                "text": "Distance traveled is the metaphorical distance that represents the journey an applicant undertakes throughout their life, encompassing achievements, personal identity, and the competencies developed along the way. Based on your experiences and your distance traveled, please describe any adversities, challenges, and/or marginalized experiences that you have encountered. Optional.",
            },
            {
                "title": "Distance Traveled - Effect and Growth",
                "limit": "1000 characters",
                "themes": ["challenge"],
                "text": "Please describe the effect of these adversities, challenges, and/or marginalized experiences on you as an individual. Explain how you overcame them, what skills you built, what lessons you learned, and how these experiences motivated you to be a doctor. Optional.",
            },
            {
                "title": "Privilege and Health Equity",
                "limit": "1000 characters",
                "themes": ["service", "diversity-equity"],
                "text": "Can you describe a time when you recognized your privilege and used it to promote health equity? Please share specific initiatives, projects, or actions in which you were involved in and the impact they had. Optional.",
            },
        ],
    },
    {
        "name": "Chicago Medical School at Rosalind Franklin University of Medicine and Science",
        "slug": "rosalind-franklin",
        "secondary_cycle": "2026-2027 live secondary portal prompts provided by applicant on 2026-07-08",
        "secondary_deadline": "December 1, 2025",
        "official_url": "https://www.rosalindfranklin.edu/admission-aid/",
        "prompt_source": "https://apply.rosalindfranklin.edu/account/login?pid=DjGKtUA_2gun6MIWwUQ2nmmoQVu1vCgWBHkHX-FUK7JrgrcSk-VZSDtnHOpbDLa02fdpuIyjLko",
        "notes": "Updated from the applicant's Rosalind Franklin secondary portal. Five concise 150-word prompts focused on service, school fit, regional fit, contribution, and feedback.",
        "prompts": [
            {
                "title": "Service, Collaboration, and Community Engagement",
                "limit": "150 words",
                "themes": ["service", "teamwork", "community"],
                "text": "Chicago Medical School values service, interprofessional collaboration, and community engagement. Describe an experience that reflects one or more of these values and how you hope to continue this work during your time in medical school.",
            },
            {
                "title": "Why Chicago Medical School",
                "limit": "150 words",
                "themes": ["why-school", "mission-fit"],
                "text": "Which specific programs, opportunities, or aspects of Chicago Medical School at Rosalind Franklin University motivated you to apply, and how do they align with your career goals?",
            },
            {
                "title": "Chicago and North Chicago Region",
                "limit": "150 words",
                "themes": ["why-school", "regional-fit"],
                "text": "What interests you about training in the Chicago/North Chicago region, and how might this environment shape your medical education and future career as a physician?",
            },
            {
                "title": "Learning Environment Contribution",
                "limit": "150 words",
                "themes": ["community", "mission-fit"],
                "text": "If you joined the Chicago Medical School community, how would you contribute to the learning environment through initiatives, organizations, or areas of involvement that interest you?",
            },
            {
                "title": "Difficult or Unexpected Feedback",
                "limit": "150 words",
                "themes": ["challenge", "values"],
                "text": "Describe a time when you received difficult or unexpected feedback about your academic performance or behavior. How did you respond to that feedback, and what changes did you make as a result?",
            },
        ],
    },
    {
        "name": "New York Medical College",
        "slug": "new-york-medical-college",
        "secondary_cycle": "2024 archive on Admit.org",
        "secondary_deadline": "December 15, 2025",
        "official_url": "https://www.nymc.edu/school-of-medicine-som/admissions/",
        "prompt_source": "https://med.admit.org/secondary-essays/new-york-medical-college",
        "notes": "Secondary is mostly attestation and context oriented rather than classic narrative essays.",
        "prompts": [
            {
                "title": "Family Connection",
                "limit": "No word limit",
                "themes": ["additional-info"],
                "text": "If you have family members with a connection to NYMC as alumni, faculty, or employees of the School of Medicine, indicate the relationship and applicable connection details.",
            },
            {
                "title": "Social Media Policy Explanation",
                "limit": "No word limit",
                "themes": ["additional-info"],
                "text": "Please review the NYMC Social Media Policy. If you select YES, we ask that you briefly explain what has been posted.",
            },
            {
                "title": "COVID Disruptions",
                "limit": "No word limit",
                "themes": ["additional-info"],
                "text": "Please share any disruptions in your academic, volunteer, work, and/or personal life related to COVID-19 that you would like the Admissions Committee to consider.",
            },
            {
                "title": "Technical Standards Attestation",
                "limit": "No word limit",
                "themes": ["additional-info"],
                "text": "Please review the NYMC Technical Standards on the admissions website and attest to your understanding of them.",
            },
        ],
    },
    {
        "name": "University of California, Riverside School of Medicine",
        "slug": "uc-riverside",
        "secondary_cycle": "2024 archive on Admit.org",
        "secondary_deadline": "October 15, 2025",
        "official_url": "https://medschool.ucr.edu/admissions",
        "prompt_source": "https://med.admit.org/secondary-essays/university-of-california-riverside-school-of-medicine",
        "notes": "Mission-forward and strongly regional; these drafts should explicitly mention underserved Inland Southern California where appropriate.",
        "prompts": [
            {
                "title": "Mission Fit and Class Contribution",
                "limit": "250 words",
                "themes": ["mission-fit", "service"],
                "text": "The mission of the UCR School of Medicine is to improve the health of the people of California and, especially, to serve Inland Southern California by training a diverse workforce of physicians and by developing innovative research and health care delivery programs that will improve the health of the medically underserved in the region and become models to be emulated throughout the state and nation. What experiences, skills, and abilities will you bring to the class to fulfill this mission?",
            },
            {
                "title": "School Value in Practice",
                "limit": "250 words",
                "themes": ["values"],
                "text": "The values of the UCR SOM are integrity, innovation, inclusion, excellence, accountability and respect. Please choose one of the values and tell us how you have personally experienced it or have seen it emulated in a clinical setting.",
            },
            {
                "title": "Future Healthcare Setting",
                "limit": "250 words",
                "themes": ["future-goals"],
                "text": "In what type of healthcare setting do you see yourself practicing medicine?",
            },
            {
                "title": "Personal Challenge, Resilience, and Grit",
                "limit": "250 words",
                "themes": ["challenge"],
                "text": "Tell us about a personal challenge you have faced in your life thus far and how you demonstrated resilience and grit to overcome it. Please do not write about studying for or taking the MCAT.",
            },
            {
                "title": "Anything Else",
                "limit": "250 words",
                "themes": ["additional-info"],
                "text": "If there is anything you would like the committee to consider about your candidacy that is not explained elsewhere in your application, please use this space to tell us.",
            },
        ],
    },
    {
        "name": "California University of Science and Medicine",
        "slug": "cusm",
        "secondary_cycle": "2025-2026 from Admit.org / Med School Insiders",
        "secondary_deadline": "December 30, 2025",
        "official_url": "https://cusm.edu/admissions/",
        "prompt_source": "https://med.admit.org/secondary-essays/california-university-of-science-and-medicine",
        "notes": "Very short prompts; best handled as polished mini-essays with clean thematic separation.",
        "prompts": [
            {
                "title": "Diversity Contribution",
                "limit": "150 words",
                "themes": ["diversity-equity"],
                "text": "Diversity comes in many forms. How do you think you might contribute to the diversity of the class?",
            },
            {
                "title": "Criticism",
                "limit": "150 words",
                "themes": ["challenge", "values"],
                "text": "Describe the last time you were criticized by a peer or supervisor. How did you handle it?",
            },
            {
                "title": "Working with a Difficult Person",
                "limit": "150 words",
                "themes": ["teamwork", "challenge"],
                "text": "Give an example of when you had to work with someone who was difficult to get along with. Why was this person difficult? How did you handle that person?",
            },
            {
                "title": "Integrity",
                "limit": "150 words",
                "themes": ["values"],
                "text": "What would be the best example that shows you are a person of integrity?",
            },
            {
                "title": "Ten Years from Now",
                "limit": "150 words",
                "themes": ["future-goals"],
                "text": "If given the opportunity to attend medical school, where would you see yourself in ten years?",
            },
            {
                "title": "Underloaded Terms Explanation",
                "limit": "150 words",
                "themes": ["academic-context"],
                "text": "If you were enrolled in fewer than 12 units or credits for more than 1 semester or 2 quarters during your undergraduate education, please provide a brief explanation. If not applicable, enter N/A.",
            },
        ],
    },
    {
        "name": "Nova Southeastern University Dr. Kiran C. Patel College of Allopathic Medicine",
        "slug": "nova-southeastern-md",
        "secondary_cycle": "2026-2027 live secondary portal prompts provided by applicant on 2026-07-14",
        "secondary_deadline": "January 31, 2026",
        "official_url": "https://md.nova.edu/admissions/md/",
        "prompt_source": "https://gateway.aamc.liaisoncas.com/app-gateway/#/login/80515/6387",
        "notes": "Updated from the applicant's Nova Southeastern MD secondary portal. Live set contains four prompts focused on teamwork, PBL readiness, unique perspective, and advanced academic/service-learning preparation.",
        "prompts": [
            {
                "title": "Teamwork Toward a Common Objective",
                "limit": "Not listed in portal text provided",
                "themes": ["teamwork", "values"],
                "text": "Please provide an example that indicates your ability to function effectively as a productive member of a team working toward a common objective. Elaborate on leadership roles you held in this capacity and how you solved problems that arose. Indicate highlights learned from this experience.",
            },
            {
                "title": "Problem Solving in Team or PBL Environment",
                "limit": "Not listed in portal text provided",
                "themes": ["teamwork", "challenge"],
                "text": "Please share some personal examples of problem solving in a team environment and/or leadership experience that would lead to your success in a Problem Based Learning environment.",
            },
            {
                "title": "Unique Perspective",
                "limit": "Not listed in portal text provided",
                "themes": ["diversity-equity", "values"],
                "text": "At the NSU MD program, we value the unique perspective that each applicant brings. Identify any traits, life experiences, or interests that a professor or advisor would not normally know about you.",
            },
            {
                "title": "Advanced Academic Work and Humanism",
                "limit": "Not listed in portal text provided",
                "themes": ["academic-context", "service"],
                "text": "How has your academic work beyond the “traditional” pre-medical school requirements (i.e., introductory biology, general chemistry, organic chemistry, and introductory physics) prepared you for medical school and for a career in medicine? Please highlight any service-learning activities that align with humanism in medicine.",
            },
        ],
    },
    {
        "name": "Roseman University College of Medicine",
        "slug": "roseman",
        "secondary_cycle": "2025-2026 from SDN school-specific thread",
        "secondary_deadline": "See secondary invite",
        "official_url": "https://www.roseman.edu/academic-programs/college-of-medicine/doctor-of-medicine-md/",
        "prompt_source": "https://forums.studentdoctor.net/threads/2025-2026-roseman.1508062/",
        "notes": "Newer Nevada program with surprisingly favorable accepted-stat profile and clear community-accountability language.",
        "prompts": [
            {
                "title": "Obstacles on the Journey to Medicine",
                "limit": "500 to 1000 words",
                "themes": ["challenge"],
                "text": "Please describe any obstacles that you have encountered during your journey to a career in medicine and how you overcame them.",
            },
            {
                "title": "Social Determinants of Health in Future Practice",
                "limit": "500 to 1000 words",
                "themes": ["service", "diversity-equity"],
                "text": "RUCOM recognizes the importance of Social Determinants of Health as key drivers of healthcare outcomes, including those in Nevada. As a future physician, how would you seek to address these Social Determinants of Health in your future practice?",
            },
            {
                "title": "Cross-Cultural Interaction",
                "limit": "500 to 1000 words",
                "themes": ["diversity-equity", "community"],
                "text": "Describe your interactions with someone from a different cultural background or life experience and what you learned from that interaction.",
            },
            {
                "title": "Gap Time Explanation",
                "limit": "250 words",
                "themes": ["gap-year"],
                "text": "If you took time off between earning your baccalaureate degree and applying to medical school, please explain why.",
            },
            {
                "title": "Application Updates",
                "limit": "250 to 1000 words",
                "themes": ["additional-info"],
                "text": "Please include any updates to your application that you would like the Admissions Committee to consider when reviewing your file. This may include changes since the submission of your primary application, information not addressed in previous questions, or additional insights into your academic journey thus far.",
            },
        ],
    },
    {
        "name": "Hackensack Meridian School of Medicine",
        "slug": "hackensack-meridian",
        "secondary_cycle": "2025-2026 from SDN school-specific thread",
        "secondary_deadline": "See secondary invite",
        "official_url": "https://www.hmsom.edu/en/admissions",
        "prompt_source": "https://forums.studentdoctor.net/threads/2025-2026-hackensack-meridian.1508026/",
        "notes": "Private New Jersey option with a cleaner MSAR profile than many similar-tier schools, but plan for a potentially slow screening timeline.",
        "prompts": [
            {
                "title": "Why Hackensack Meridian",
                "limit": "500 words",
                "themes": ["why-school"],
                "text": "Why are you interested in attending the Hackensack Meridian School of Medicine?",
            },
            {
                "title": "Engaging with Difference",
                "limit": "500 words",
                "themes": ["diversity-equity", "community"],
                "text": "Describe a time when you engaged with a perspective, culture, or experience different from your own. What did you learn, and how did it influence your personal or professional development?",
            },
            {
                "title": "Preparation for Advanced Study in Medicine",
                "limit": "500 words",
                "themes": ["clinical", "future-goals", "research"],
                "text": "Describe your experience with the field of medicine (or a related field) that has prepared you for advanced study in this area. Specifically, how have your life experiences prepared you to pursue a degree in medicine, including: coursework, clinical work, experiences in overcoming adversity, work opportunity, volunteer activities, and/or research experiences?",
            },
        ],
    },
    {
        "name": "Thomas F. Frist, Jr. College of Medicine at Belmont University",
        "slug": "belmont-frist",
        "secondary_cycle": "2025-2026 from Belmont application page / SDN school-specific thread",
        "secondary_deadline": "Submit within 10 days of receipt when possible",
        "official_url": "https://www.belmont.edu/medicine/admissions/application.html",
        "prompt_source": "https://forums.studentdoctor.net/threads/2025-2026-belmont-frist.1508022/",
        "notes": "Newer private Tennessee school with no in-state preference and a mission profile that rewards service, humility, and thoughtful reflection.",
        "prompts": [
            {
                "title": "Most Energizing Belmont Value",
                "limit": "2000 characters",
                "themes": ["values", "mission-fit"],
                "text": "At FCoM, our mission, vision, and values shape our purpose, set our aspirations, and inform our decisions. Please select which value you find most energizing and why. Discuss how this value has impacted your life. Values: We love learning, Lead by serving, Live with integrity, Heal together in humility, and Welcome difference.",
            },
            {
                "title": "Spiritual Experiences, Faith, or Personal Beliefs",
                "limit": "2000 characters",
                "themes": ["values", "future-goals"],
                "text": "Our curriculum centers around a whole-person approach to healing in a community of service-learning, inspired by the love and grace of Christ. Discuss how your spiritual experiences, faith, or personal beliefs have influenced your life and your decision to pursue medicine as a career.",
            },
            {
                "title": "Embracing Ambiguity in a New Community",
                "limit": "2000 characters",
                "themes": ["challenge", "community"],
                "text": "As a newer medical school, our students will help shape a new culture and build lasting community. Reflect on a time when you embraced ambiguity, sharing specific examples where you contributed to creating a culture of growth, collaboration, and adaptability.",
            },
            {
                "title": "Reapplicant Changes",
                "limit": "2000 characters",
                "themes": ["additional-info", "gap-year"],
                "text": "Reapplicants only: Describe the changes to your application from previous cycles, including developments to your academics, experiences, and/or personal attributes.",
            },
        ],
    },
    {
        "name": "University of Illinois College of Medicine",
        "slug": "uicom",
        "secondary_cycle": "2025-2026 from Med School Insiders",
        "secondary_deadline": "October 31, 2025",
        "official_url": "https://medicine.uic.edu/admissions/",
        "prompt_source": "https://medschoolinsiders.com/medical-school-secondary-prompts-database/university-of-illinois-college-of-medicine-secondary-essay-prompts/",
        "notes": "Public school with some out-of-state risk, but current prompts align unusually well with your justice, diversity, and campus-research interests.",
        "prompts": [
            {
                "title": "Conflict and Change",
                "limit": "No character limit indicated",
                "themes": ["challenge", "values"],
                "text": "What characteristics, qualities, or attributes do you possess that have helped you to deal with conflict and change?",
            },
            {
                "title": "Why UICOM",
                "limit": "No character limit indicated",
                "themes": ["why-school"],
                "text": "Which characteristics, qualities, or attributes of UICOM attracted you to apply for medical school here?",
            },
            {
                "title": "Two Campuses",
                "limit": "No character limit indicated",
                "themes": ["why-school", "mission-fit"],
                "text": "An important part of UICOM's identity is the concept of \"one college, three campuses.\" The curriculum is identical on each campus; however, each campus has unique characteristics. Please describe what you have learned about at least two of our three campuses.",
            },
            {
                "title": "Prejudice, Injustice, and the Bystander",
                "limit": "No character limit indicated",
                "themes": ["diversity-equity", "values"],
                "text": "What are some of the causes and consequences of prejudice and injustice? What does an individual's response to prejudice and injustice reveal about their character? What is the role of a bystander who witnesses prejudice or injustice?",
            },
            {
                "title": "Perspective and Contribution to UICOM",
                "limit": "No character limit indicated",
                "themes": ["diversity-equity", "community"],
                "text": "UICOM values a wide range of perspectives. Describe an aspect of your own perspective, value system, or lived experience that is important to you and how it would contribute to the diverse and collaborative community at UICOM.",
            },
            {
                "title": "Reapplicant Update",
                "limit": "No character limit indicated",
                "themes": ["additional-info", "gap-year"],
                "text": "If you are reapplying this year please describe what you have done during the past year.",
            },
            {
                "title": "Incomplete Prior Program",
                "limit": "No character limit indicated",
                "themes": ["academic-context", "additional-info"],
                "text": "If you have ever matriculated into and not completed a professional/graduate program, please describe the circumstances of why you did not complete the program of study.",
            },
        ],
    },
    {
        "name": "George Washington University School of Medicine & Health Sciences",
        "slug": "george-washington",
        "secondary_cycle": "2025-2026 from Med School Insiders",
        "secondary_deadline": "December 11, 2025",
        "official_url": "https://smhs.gwu.edu/academics/md-program/admissions",
        "prompt_source": "https://medschoolinsiders.com/medical-school-secondary-prompts-database/george-washington-secondary-essay-prompts/",
        "notes": "Strong service, advocacy, public health, and policy fit, but the live MSAR stats make this a reach rather than a true odds-improver.",
        "prompts": [
            {
                "title": "Regional Medical Campus Interest",
                "limit": "1750 characters excluding spaces",
                "themes": ["why-school", "mission-fit"],
                "text": "If you selected regional medical campus preferred or regional medical campus only, please explain in detail your interest in regional medical campus and how it will be a good fit for your clinical education.",
            },
            {
                "title": "Application Through Matriculation Activities",
                "limit": "750 characters excluding spaces",
                "themes": ["gap-year", "clinical", "service"],
                "text": "Please provide the Admissions Committee with a brief summary of your activities, academics, employment or other occupations to account for full-time activity, approximately 30-40 hours per week, from the point of application through matriculation.",
            },
            {
                "title": "Clinical Public Health Interests",
                "limit": "350 characters excluding spaces",
                "themes": ["service", "mission-fit"],
                "text": "The MD Program includes substantial content in Clinical Public Health, including population health, health systems science, health policy, and community health, to prepare GW graduates for an expanded scope of practice required to be successful 21st century physicians. What are your specific interests and experiences related to that aspect of the MD Program?",
            },
            {
                "title": "Uniqueness, Challenges, and Learning",
                "limit": "750 characters excluding spaces",
                "themes": ["challenge", "diversity-equity", "values"],
                "text": "What makes you a unique individual? What challenges have you faced? What have you learned from your experiences?",
            },
            {
                "title": "Specific Interest in GW",
                "limit": "1750 characters excluding spaces",
                "themes": ["why-school", "mission-fit"],
                "text": "What is your specific interest in the MD Program at GW? What opportunities would you take advantage of as a student here? Why?",
            },
            {
                "title": "Prior Admissions Office Interaction",
                "limit": "No character limit indicated",
                "themes": ["additional-info"],
                "text": "Have you previously interacted directly with the MD Admissions Office through events, tours, fairs, webinars, or interviews? If yes, please explain.",
            },
            {
                "title": "Joint MD MPH Interest",
                "limit": "No character limit indicated",
                "themes": ["future-goals", "mission-fit"],
                "text": "Do you want to pursue the joint MD/MPH program? If yes, please describe why you would want to pursue the MD/MPH program and how the combined degree would fit into your career goals.",
            },
        ],
    },
    {
        "name": "California Northstate University College of Medicine",
        "slug": "california-northstate",
        "secondary_cycle": "2024-2025 latest public SDN prompt set",
        "secondary_deadline": "January 22, 2027 in cached 2027 MSAR",
        "official_url": "https://medicine.cnsu.edu/admissions/",
        "prompt_source": "https://www.studentdoctor.net/schools-database/medical-school/essay-questions/CAL-NO",
        "notes": "California MD option with favorable geography, but review financing carefully because the official admissions page says CNU does not participate in federal direct student loan programs.",
        "prompts": [
            {
                "title": "Why CNUCOM",
                "limit": "No word count specified in latest public prompt set",
                "themes": ["why-school", "mission-fit"],
                "text": "Why have you chosen to apply to CNUCOM?",
            },
            {
                "title": "Education Not Continuous",
                "limit": "No word count specified in latest public prompt set",
                "themes": ["gap-year", "academic-context"],
                "text": "If your education has not been continuous since high school, please explain why. Examples of discontinuities include time taken off while obtaining your undergraduate degree, in addition to gap years.",
            },
            {
                "title": "Reapplicant Accomplishments",
                "limit": "No word count specified in latest public prompt set",
                "themes": ["additional-info", "gap-year"],
                "text": "If you have previously applied to medical school, what have you accomplished since that time that would warrant your admission now?",
            },
            {
                "title": "Anything Else",
                "limit": "No word count specified in latest public prompt set",
                "themes": ["additional-info"],
                "text": "Is there anything you would like the Admissions Committee to know that is not reflected elsewhere in your application?",
            },
            {
                "title": "Pre-Health Advisor Experience",
                "limit": "No word count specified in latest public prompt set",
                "themes": ["values", "academic-context"],
                "text": "Did you have a Pre-Health Advisor at your undergraduate institution? If so, please tell us about your experience. How did it help you in your journey to apply to medical school? If not, please let us know how you worked independently to find out more about applying to medical school and the path of your journey to apply.",
            },
            {
                "title": "Future Direction of Healthcare",
                "limit": "No word count specified in latest public prompt set",
                "themes": ["future-goals", "values"],
                "text": "In which direction would you like to see healthcare progress over the next decade?",
            },
            {
                "title": "Standardized Tests and MCAT Preparation",
                "limit": "No word count specified in latest public prompt set",
                "themes": ["academic-context", "values"],
                "text": "How do you feel about standardized tests? How did you prepare for the MCAT? What tools or preparatory courses/material did you use and how did you study? Do you feel like your score reflects how you will perform in medical school? From what you have learned, do you think it will help you in the way you will study or prepare for USMLE exams?",
            },
        ],
    },
]
